### ISSUE TITLE
Need to adjust links after rename

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap-Documentation#3]
Since a lot of the internal links still use the `carnap-` prefix.

**Comment by rzach** [comment]
I've changed all the links to the new file names. I'm assuming `[...](file.md)` will be a relative link which will point to the same URL as `[...](./file.md)` and `[...](/slug)` will point to `https://carnap.io/slug`.

**Comment by lf-** [comment]
@rzach relative addressing of URLs for Carnap like that would be incorrect if you're browsing on GitHub I think. May have to make them absolute. The relative links to other docs seem to all work as you suggest on both platforms based on my testing with the docs I put in.

**Comment by rzach** [comment]
Right, "/slug" doesn't work on Github. I think that's better than absolute URLs since those will all break if you deploy the whole thing not on `carnap.io`.

**Comment by gleachkr** [comment]
Looks like the internal links are working on both github and carnap.io. Ready to close?

**Comment by rzach** [comment]
Yes!
