### ISSUE TITLE
AllenSL

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap-Documentation#8]
Cool page for the documentation. I wouldn't say that this is in urgent need of documentation, but if, eventually, you want the list to be complete, I've been using AllenSL. (It's sort of based on the rules in Allen & Hand's Logic Primer, and it goes with the version of Forall x that my students use). After Graham got it rolling, I described it here: http://blog.loighic.net/the-allensl-system-in-carnap.  You can take anything you want from there, or, when I have a chance, I can write up a documentation page that would be appropriate for Carnap.io. 

Greg

**Comment by rzach** [comment]
Done in commit 51e398af53a49613c908c3bcfc86614a2afebeea

**Comment by rzach** [comment]
See https://carnap.io/srv/doc/forallx-msu.md

**Comment by loighic** [comment]
Whoa, nice page. Thanks. (I meant to contribute something myself, but, you know, time.)
