### ISSUE TITLE
Can doc files be downloaded?

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap-Documentation#9]
In `doc/pandoc.md` https://carnap.io/srv/doc/pandoc.md it says the file can be downloaded at https://carnap.io/srv/doc/pandoc.md/download 
That link doesn't work. Should it? If not, I'll link to the source of `pandoc.md` on GitHub instead.

**Comment by gleachkr** [comment]
Nope, that's a holdover from when these were shared documents. That fix sounds good, thanks!
